# Generated by Django 5.1.4 on 2024-12-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='bounds',
            field=models.JSONField(blank=True, null=True, verbose_name='Межі району'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='bounds',
            field=models.JSONField(blank=True, null=True, verbose_name='Межі населеного пункту'),
        ),
    ]
