# Generated by Django 5.1.4 on 2024-12-31 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0003_alter_settlement_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='settlements.region', verbose_name='Область'),
        ),
    ]
