# Generated by Django 5.1.4 on 2024-12-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0004_settlement_region'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settlement',
            unique_together={('name', 'district', 'region')},
        ),
    ]
