# Generated by Django 5.1.4 on 2025-01-02 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL, verbose_name='Творець'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='is_confirmed',
            field=models.BooleanField(default=True, help_text='Підтверджено модератором', verbose_name='Підтверджено'),
        ),
    ]
